name       : jet
version    : 0.5.25
release    : 4
source     :
    - https://github.com/borkdude/jet/archive/refs/tags/v0.5.25.tar.gz : 9054dfd4406c4fb034c68eddda0996ca238345bd97695e579a7c0fdeeb639ab0
license    : EPL-1.0
networking : yes
component  : programming.tools
summary    : Transform EDN transit and json from the command line.
description: |
    CLI to transform between JSON, EDN and Transit, powered with a minimal query language.
builddeps  :
    - leiningen
    - graalvm
environment: |
    export GRAALVM_HOME=/usr/share/graalvm
    export JAVA_HOME=/usr/share/graalvm/
    export JAVA_CMD=/usr/share/graalvm/bin/java
build      : |
    # make lein use a temporary location for deps
    sed -i '5 i :local-repo "/tmp/.m2/repo"' project.clj
    lein uberjar
    ./script/compile
install    : |
    install -Dm00755 ./jet $installdir/usr/bin/jet
