name       : jet
version    : 0.1.0
release    : 2
source     :
    - https://github.com/borkdude/jet/archive/refs/tags/v0.1.0.tar.gz : faed01c3d31631332fa60fd6f1bb39ae4a2f6cfc396a8747d5cfce4f1053a99c
license    : EPL-1.0
networking : yes
component  : programming.tools
summary    : Transform EDN transit and json from the command line.
description: |
    CLI to transform between JSON, EDN and Transit, powered with a minimal query language.
builddeps  :
    - leiningen
    - graalvm
    - openjdk-17
environment: |
    export GRAALVM_HOME=/usr/share/graalvm/
    export JAVA_HOME=/usr/share/graalvm/
    export JAVA_CMD=/usr/lib64/openjdk-17/bin/java
build      : |
    # make lein use a temporary location for deps
    sed -i '5 i :local-repo "/tmp/.m2/repo"' project.clj
    lein uberjar
    ./script/compile
install    : |
    install -Dm00755 ./jet $installdir/usr/bin/jet
